DigiGymWebApp_HDip/Controllers/ClientController.cs
using DigiGymWebApp_HDip.Data;
using DigiGymWebApp_HDip.Models;
using DigiGymWebApp_HDip.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace DigiGymWebApp_HDip.Controllers
{
    [Authorize(Policy = "ClientOnly")]
    public class ClientController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole>_roleManager;
        private readonly IBMIService _bmiService;
        private readonly IBMICategory _bmiCategory;

        public ClientController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager, IBMIService bmiService, IBMICategory bmiCategory)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
            _bmiService = bmiService;
            _bmiCategory = bmiCategory;
            _context.Database.EnsureCreated();
        }

        public async Task<IActionResult> Create()
        {
            var enumGenderTypeValues = Enum.GetValues(typeof(GenderTypes));
            var selectListGenderType = new SelectList(enumGenderTypeValues);

            ViewBag.GenderType = selectListGenderType;

            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UserProfile profile)
        {
            if (ModelState.IsValid)
            {
                // attribute user to record
                var userId = _userManager.GetUserId(User);
                profile.Id = userId;

                _context.Add(profile);
                await _context.SaveChangesAsync();

                return RedirectToAction("Confirm", profile);
            }
            return View();
        }

        public async Task<IActionResult> Confirm(UserProfile profile)
        {
            return View(profile);
        }

        public async Task<IActionResult> Edit(int? id)
        {   
            var userId = _userManager.GetUserId(User);
            var profileEntry = await _context.ProfileEntries
                                  .Where(p => p.ProfileID == id && p.Id == userId)
                                  .AsNoTracking()
                                  .FirstOrDefaultAsync();

            var enumGenderTypeValues = Enum.GetValues(typeof(GenderTypes));
            var selectListGenderType = new SelectList(enumGenderTypeValues, profileEntry.Gender);

            ViewBag.Gender = selectListGenderType;

            return View(profileEntry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProfileID,Height,Gender")] UserProfile profileEntry)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var existingProfileEntry = await _context.ProfileEntries
                                                  .Where(p => p.ProfileID == id && p.Id == userId)
                                                  .FirstOrDefaultAsync();

                if (existingProfileEntry == null)
                {
                    return NotFound();
                }

                existingProfileEntry.Height = profileEntry.Height;
                existingProfileEntry.Gender = profileEntry.Gender;
                
                _context.Update(existingProfileEntry);
                await _context.SaveChangesAsync();

                return RedirectToAction("Profile");
            }

            // If ModelState not valid, handle ViewBag properties
            var enumGenderTypeValues = Enum.GetValues(typeof(GenderTypes));
            var selectListGenderType = new SelectList(enumGenderTypeValues, profileEntry.Gender);
            ViewBag.Gender = selectListGenderType;

            return View(profileEntry);
        }

        public async Task<IActionResult> Profile(DateTime date)
        {
            var userId = _userManager.GetUserId(User);
            var profileEntry = await _context.ProfileEntries
                                        // leverage navigation property in View
                                        .Include(p => p.User)
                                        .Where(p => p.Id == userId)
                                        .FirstOrDefaultAsync();

            // get latest weight entry
            var weightEntry = await _context.WeightEntries
                                        .Include(p => p.User)
                                        .Where(p => p.Id == userId)
                                        .OrderByDescending(w => w.Timestamp)
                                        .FirstOrDefaultAsync();

            ViewBag.WeightEntry = weightEntry;

            // make BMI value available
            var bmiService = await _bmiService.GetBMI(date, userId);
            ViewBag.BMIService = bmiService;

            var bmiCategory = await _bmiCategory.GetBMICategory(bmiService);
            ViewBag.BMICategory = bmiCategory;

            return View(profileEntry);
        }
    }
}

DigiGymWebApp_HDip/Controllers/WeightController.cs
using DigiGymWebApp_HDip.Data;
using DigiGymWebApp_HDip.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DigiGymWebApp_HDip.Controllers
{
    [Authorize(Policy = "ClientOnly")]
    public class WeightController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public WeightController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _context.Database.EnsureCreated();
        }

        public async Task<IActionResult> WeightEntries()
        {
            var userId = _userManager.GetUserId(User);
            var weightEntries = await _context.WeightEntries
                                              .OrderBy(w => w.Timestamp)
                                              .Where(we => we.Id == userId)
                                              .ToListAsync();
            return View(weightEntries);
        }

        public async Task<IActionResult> Create()
        {
            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WeightEntry weightEntry)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                weightEntry.Id = userId;
                weightEntry.Timestamp = DateTime.Now;

                _context.Add(weightEntry);
                await _context.SaveChangesAsync();

                return RedirectToAction("Confirm", weightEntry);
            }
            return View();
        }

        public async Task<IActionResult> Confirm(WeightEntry weightEntry)
        {
            return View(weightEntry);
        }

        public async Task<IActionResult> Chart()
        {
            var userId = _userManager.GetUserId(User);
            var allWeight = await _context.WeightEntries
                                .OrderBy(w => w.Timestamp)
                                .Where(x => x.Id == userId)
                                .ToListAsync();
            return View(allWeight);
        }

        public async Task<IActionResult> Details(int id)
        {
            var userId = _userManager.GetUserId(User);
            var weightEntry = await _context.WeightEntries
                                  .Where(w => w.WeightID == id && w.Id == userId)
                                  .FirstOrDefaultAsync();
            if (weightEntry == null)
            {
                return NotFound();
            }
            return View(weightEntry);
        }
        
        public async Task<IActionResult> Delete(int id)
        {
            var userId = _userManager.GetUserId(User);
            var weightEntry = await _context.WeightEntries
                                          .Where(f => f.WeightID == id && f.Id == userId)
                                          .FirstOrDefaultAsync();
            _context.Remove(weightEntry);
            await _context.SaveChangesAsync();

            return RedirectToAction("WeightEntries");
        }

        public async Task<IActionResult> Edit(int? id)
        {   
            var userId = _userManager.GetUserId(User);
            var weightEntry = await _context.WeightEntries
                                  .Where(f => f.WeightID == id && f.Id == userId)
                                  .AsNoTracking()
                                  .FirstOrDefaultAsync();
            return View(weightEntry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WeightID,Weight,Timestamp")] WeightEntry weightEntry)
        {
            if (ModelState.IsValid)
            { 
                var userId = _userManager.GetUserId(User);
                var existingWeightEntry = await _context.WeightEntries
                                                  .Where(f => f.WeightID == id && f.Id == userId)
                                                  .FirstOrDefaultAsync();

                existingWeightEntry.Weight = weightEntry.Weight;

                _context.Update(existingWeightEntry);
                await _context.SaveChangesAsync();

                // redirect to details page of item after editing item
                return RedirectToAction("Details", new { id = weightEntry.WeightID });
            }
            return View();
        }
    }
}

DigiGymWebApp_HDip/Views/Weight/Chart.cshtml
@model IEnumerable<DigiGymWebApp_HDip.Models.WeightEntry>
@using System.Text.Json

@{
    ViewData["Title"] = "Chart";
}

<div class="container">
    <div class="row">
        <div class="pre-footer chart-container">
            <h2 class="text-center mt-3">Weight Chart</h2>
            <p class="text-center dashed pb-3">
                See how your weight progresses over time.
            </p>
            <div class="weightChartContainerMain">
                <canvas id="weightChart"></canvas>
            </div>

            <!-- Hidden elements to hold the JSON data -->
            <div id="weightData" style="display: none;">@Html.Raw(JsonSerializer.Serialize(Model.Select(x => x.Weight)))</div>
            <div id="dateData" style="display: none;">@Html.Raw(JsonSerializer.Serialize(Model.Select(x => x.Timestamp.ToString("yyyy-MM-dd"))))</div>

            <div class="text-center pt-4">
                <a asp-controller="Weight" asp-action="WeightEntries">All Weights</a>
            </div>
        </div>
    </div>
</div>

DigiGymWebApp_HDip/Views/Weight/Confirm.cshtml
@model DigiGymWebApp_HDip.Models.WeightEntry

@{
    ViewData["Title"] = "Confirm";
}

<div class="container">
    <div class="row">

        <h1 class="text-center dashed py-3">Confirmation</h1>

        <div class="text-center">
            <dl class="row">
                <dt class="col-sm-6 text-lg-end">
                    @Html.DisplayNameFor(model => model.Weight)
                </dt>
                <dd class="col-sm-6 text-lg-start">
                    @Html.DisplayFor(model => model.Weight)
                </dd>
                <dt class="col-sm-6 text-lg-end">
                    @Html.DisplayNameFor(model => model.Timestamp)
                </dt>
                <dd class="col-sm-6 text-lg-start">
                    @Html.DisplayFor(model => model.Timestamp)
                </dd>
            </dl>
            <div class="text-center">
                <a asp-action="Edit" asp-route-id="@Model?.WeightID">Edit</a> |
                <a asp-action="WeightEntries">All Weights </a> |
                <a asp-controller="Client" asp-action="Profile">Back to Profile </a> |
            </div>
            <div class="text-center">
                <a asp-action="Chart">See Progress chart</a>
            </div>
        </div>

    </div>
</div>

DigiGymWebApp_HDip/Views/Weight/Create.cshtml
@model DigiGymWebApp_HDip.Models.WeightEntry

@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row">
        <h1 class="dashed text-center py-3">Create Weight Entry</h1>

        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Weight" class="control-label"></label>
                        <input asp-for="Weight" class="form-control" />
                        <span asp-validation-for="Weight" class="text-danger"></span>
                    </div>
                    <div class="form-group my-3 text-center">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
                <div class="text-center">
                    <a asp-action="WeightEntries">All Weights</a>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>



    </div>
</div>

DigiGymWebApp_HDip/Views/Weight/Details.cshtml
@model DigiGymWebApp_HDip.Models.WeightEntry

@{
    ViewData["Title"] = "Details";
}

<div class="container text-center">
    <div class="row">
        <h1 class="dashed py-3 text-center">Details</h1>

        <div>
            <dl class="row text-center">
                <dt class="col-sm-6 text-lg-end">
                    @Html.DisplayNameFor(model => model.Weight)
                </dt>
                <dd class="col-sm-6 text-lg-start">
                    @Html.DisplayFor(model => model.Weight)
                </dd>
                <dt class="col-sm-6 text-lg-end">
                    @Html.DisplayNameFor(model => model.Timestamp)
                </dt>
                <dd class="col-sm-6 text-lg-start">
                    @Html.DisplayFor(model => model.Timestamp)
                </dd>
            </dl>
            <div>
                <a asp-action="Edit" asp-route-id="@Model?.WeightID">Edit</a> |
                <a asp-action="WeightEntries">All Weights</a>
            </div>
        </div>
    </div>
</div>

DigiGymWebApp_HDip/Views/Weight/Edit.cshtml
@model DigiGymWebApp_HDip.Models.WeightEntry

@{
    ViewData["Title"] = "Edit";
}

<div class="container">
    <div class="row pre-footer text-center">
        <h1 class="dashed py-3">Edit Weight</h1>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="WeightID" />
                    <div class="form-group">
                        <label asp-for="Weight" class="control-label"></label>
                        <input asp-for="Weight" class="form-control" />
                        <span asp-validation-for="Weight" class="text-danger"></span>
                    </div>
                    <div class="form-group pt-3">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </form>
                <div class="py-3">
                    <a asp-action="WeightEntries">All Weights</a>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
</div>

DigiGymWebApp_HDip/Views/Weight/WeightEntries.cshtml
@model IEnumerable<DigiGymWebApp_HDip.Models.WeightEntry>

@{
    ViewData["Title"] = "WeightEntries";
}

<div class="container">
    <div class="row">
        <h1 class="dashed py-3 text-center">Your Weight Entries</h1>

        <p class="text-center">
            <a asp-action="Create">Create New</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Weight)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Timestamp)
                    </th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Weight)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Timestamp)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.WeightID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.WeightID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.WeightID">Delete</a>
                    </td>
                </tr>
        }
            </tbody>
        </table>

        <div class="text-center pt-4">
            <a asp-controller="Weight" asp-action="Chart">See progress chart >></a>
        </div>

    </div>
</div>