DigiGymWebApp_HDip/Controllers/FoodController.cs
using DigiGymWebApp_HDip.Data;
using DigiGymWebApp_HDip.Models;
using DigiGymWebApp_HDip.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Net.Sockets;

namespace DigiGymWebApp_HDip.Controllers
{
    [Authorize(Policy = "ClientOnly")]
    public class FoodController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ICalorieCounterService  _calorieCounterService;

        public FoodController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, ICalorieCounterService  calorieCounterService)
        {
            _context = context;
            _userManager = userManager;
            _calorieCounterService = calorieCounterService;
            _context.Database.EnsureCreated();
        }

        public async Task<ActionResult> FoodDiary(string id)
        {
            var userId = _userManager.GetUserId(User);
            var dates = await _context.FoodDiary
                .Where(f => f.Id == userId)
                .Select(f => f.CreatedAt.Date)
                 // Show single date, even if date has multiple entries
                .Distinct()
                .ToListAsync();
            return View(dates);
        }

        public async Task<ActionResult> Dates(DateTime date)
        {
            var userId = _userManager.GetUserId(User);
            var foodEntry = await _context.FoodDiary
                    .Where(f => f.CreatedAt.Date == date.Date && f.Id == userId)
                    .ToListAsync();

            var totalCalories = await _calorieCounterService.GetTotalCalories(date, userId);
            ViewBag.TotalCalories = totalCalories;


            // get macro data for pie chart
            var totalProtein = foodEntry.Sum(m => m.Protein);
            var totalCarbs = foodEntry.Sum(m => m.Carbohydrates);
            var totalFat = foodEntry.Sum(m => m.Fat);

            ViewBag.TotalProtein = totalProtein;
            ViewBag.TotalCarbs = totalCarbs;
            ViewBag.TotalFat = totalFat;

            return View(foodEntry);
        }

        public async Task<IActionResult> Create()
        {
            var enumMealTypeValues = Enum.GetValues(typeof(MealTypes));
            var selectListMealType = new SelectList(enumMealTypeValues);

            ViewBag.MealType = selectListMealType;

            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Food food)
        {
            if (ModelState.IsValid)
            {
                // Get user, string type
                var userId = _userManager.GetUserId(User);
                // Set Id property value to user's id
                food.Id = userId;
                food.CreatedAt = DateTime.Now;

                _context.Add(food);
                await _context.SaveChangesAsync();

                return RedirectToAction("Confirm", food);
            }
            return View();
        }

        public async Task<IActionResult> Confirm(Food food)
        {
            return View(food);
        }

        public async Task<IActionResult> Edit(int? id)
        {   
            var userId = _userManager.GetUserId(User);
            var foodEntry = await _context.FoodDiary
                                  .Where(f => f.FoodID == id && f.Id == userId)
                                  .AsNoTracking()
                                  .FirstOrDefaultAsync();

            var enumMealTypeValues = Enum.GetValues(typeof(MealTypes));
            var selectListMealType = new SelectList(enumMealTypeValues, foodEntry.MealType);

            ViewBag.MealType = selectListMealType;

            return View(foodEntry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FoodID,FoodName,FoodBrand,Serving,Calories,Protein,Carbohydrates,Fat,MealType,Grams,CreatedAt")] Food foodEntry)
        {
            if (ModelState.IsValid)
            { 
                var userId = _userManager.GetUserId(User);
                var existingFoodEntry = await _context.FoodDiary
                                                  .Where(f => f.FoodID == id && f.Id == userId)
                                                  .FirstOrDefaultAsync();

                existingFoodEntry.FoodID = foodEntry.FoodID;
                existingFoodEntry.FoodName = foodEntry.FoodName;
                existingFoodEntry.FoodBrand = foodEntry.FoodBrand;
                existingFoodEntry.Serving = foodEntry.Serving;
                existingFoodEntry.Calories = foodEntry.Calories;
                existingFoodEntry.Protein = foodEntry.Protein;
                existingFoodEntry.Carbohydrates = foodEntry.Carbohydrates;
                existingFoodEntry.Fat = foodEntry.Fat;
                existingFoodEntry.MealType = foodEntry.MealType;
                existingFoodEntry.Grams = foodEntry.Grams;

                _context.Update(existingFoodEntry);
                await _context.SaveChangesAsync();

                return RedirectToAction("FoodDiary");
            }
            return View(foodEntry);
        }

        public async Task<IActionResult> Details(int id)
        {
            var userId = _userManager.GetUserId(User);
            var foodEntry = await _context.FoodDiary
                                  .Where(f => f.FoodID == id && f.Id == userId)
                                  .FirstOrDefaultAsync();

            if (foodEntry == null)
            {
                return NotFound();
            }

            return View(foodEntry);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var userId = _userManager.GetUserId(User);
            var foodEntry = await _context.FoodDiary
                                          .Where(f => f.FoodID == id && f.Id == userId)
                                          .FirstOrDefaultAsync();

            _context.Remove(foodEntry);
            await _context.SaveChangesAsync();

            return RedirectToAction("FoodDiary");
        }

    }
}

DigiGymWebApp_HDip/Controllers/WaterController.cs
using DigiGymWebApp_HDip.Data;
using DigiGymWebApp_HDip.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DigiGymWebApp_HDip.Controllers
{
    [Authorize(Policy = "ClientOnly")]
    public class WaterController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public WaterController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _context.Database.EnsureCreated();
        }

        public async Task<IActionResult> WaterEntries()
        {
            var userId = _userManager.GetUserId(User);
            var waterEntries = await _context.WaterEntries
                                              .OrderBy(w => w.Timestamp)
                                              .Where(we => we.Id == userId)
                                              .ToListAsync();
            return View(waterEntries);
        }

        public async Task<IActionResult> Create()
        {
            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Water waterEntry)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                waterEntry.Id = userId;
                waterEntry.Timestamp = DateTime.Now;

                _context.Add(waterEntry);
                await _context.SaveChangesAsync();

                return RedirectToAction("Confirm", waterEntry);
            }
            return View();
        }

        public async Task<IActionResult> Confirm(Water waterEntry)
        {
            return View(waterEntry);
        }

        public async Task<IActionResult> Details(int id)
        {
            var userId = _userManager.GetUserId(User);
            var waterEntry = await _context.WaterEntries
                                  .Where(w => w.WaterID == id && w.Id == userId)
                                  .FirstOrDefaultAsync();
            if (waterEntry == null)
            {
                return NotFound();
            }
            return View(waterEntry);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var userId = _userManager.GetUserId(User);
            var waterEntry = await _context.WaterEntries
                                          .Where(f => f.WaterID == id && f.Id == userId)
                                          .FirstOrDefaultAsync();
            _context.Remove(waterEntry);
            await _context.SaveChangesAsync();
            return RedirectToAction("WaterEntries");
        }

        public async Task<IActionResult> Edit(int? id)
        {   
            var userId = _userManager.GetUserId(User);
            var waterEntry = await _context.WaterEntries
                                  .Where(f => f.WaterID == id && f.Id == userId)
                                  .AsNoTracking()
                                  .FirstOrDefaultAsync();

            return View(waterEntry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WaterID,Amount,Timestamp")] Water waterEntry)
        {
            if (ModelState.IsValid)
            { 
                var userId = _userManager.GetUserId(User);
                var existingWaterEntry = await _context.WaterEntries
                                                  .Where(f => f.WaterID == id && f.Id == userId)
                                                  .FirstOrDefaultAsync();

                existingWaterEntry.Amount = waterEntry.Amount;

                _context.Update(existingWaterEntry);
                await _context.SaveChangesAsync();

                // redirect to details page of item after editing item
                return RedirectToAction("Details", new { id = waterEntry.WaterID });
            }
            return View();
        }

        public async Task<IActionResult> Chart()
        {
            var userId = _userManager.GetUserId(User);

            // Get today's date range
            var today = DateTime.Today;
            var startOfDay = today;
            var endOfDay = today.AddDays(1).AddTicks(-1); // End of today, last moment e.g. 23:59:59.9999999

            // Fetch water entries for today
            var dailyWaterEntries = await _context.WaterEntries
                .Where(x => x.Id == userId && x.Timestamp >= startOfDay && x.Timestamp <= endOfDay)
                .ToListAsync();

            // Calculate total intake for today
            var totalIntakeToday = dailyWaterEntries.Sum(w => w.Amount);

            return View(totalIntakeToday);

        }
    }
}

DigiGymWebApp_HDip/Controllers/WeightController.cs
using DigiGymWebApp_HDip.Data;
using DigiGymWebApp_HDip.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DigiGymWebApp_HDip.Controllers
{
    [Authorize(Policy = "ClientOnly")]
    public class WeightController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public WeightController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _context.Database.EnsureCreated();
        }

        public async Task<IActionResult> WeightEntries()
        {
            var userId = _userManager.GetUserId(User);
            var weightEntries = await _context.WeightEntries
                                              .OrderBy(w => w.Timestamp)
                                              .Where(we => we.Id == userId)
                                              .ToListAsync();
            return View(weightEntries);
        }

        public async Task<IActionResult> Create()
        {
            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WeightEntry weightEntry)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                weightEntry.Id = userId;
                weightEntry.Timestamp = DateTime.Now;

                _context.Add(weightEntry);
                await _context.SaveChangesAsync();

                return RedirectToAction("Confirm", weightEntry);
            }
            return View();
        }

        public async Task<IActionResult> Confirm(WeightEntry weightEntry)
        {
            return View(weightEntry);
        }

        public async Task<IActionResult> Chart()
        {
            var userId = _userManager.GetUserId(User);
            var allWeight = await _context.WeightEntries
                                .OrderBy(w => w.Timestamp)
                                .Where(x => x.Id == userId)
                                .ToListAsync();
            return View(allWeight);
        }

        public async Task<IActionResult> Details(int id)
        {
            var userId = _userManager.GetUserId(User);
            var weightEntry = await _context.WeightEntries
                                  .Where(w => w.WeightID == id && w.Id == userId)
                                  .FirstOrDefaultAsync();
            if (weightEntry == null)
            {
                return NotFound();
            }
            return View(weightEntry);
        }
        
        public async Task<IActionResult> Delete(int id)
        {
            var userId = _userManager.GetUserId(User);
            var weightEntry = await _context.WeightEntries
                                          .Where(f => f.WeightID == id && f.Id == userId)
                                          .FirstOrDefaultAsync();
            _context.Remove(weightEntry);
            await _context.SaveChangesAsync();

            return RedirectToAction("WeightEntries");
        }

        public async Task<IActionResult> Edit(int? id)
        {   
            var userId = _userManager.GetUserId(User);
            var weightEntry = await _context.WeightEntries
                                  .Where(f => f.WeightID == id && f.Id == userId)
                                  .AsNoTracking()
                                  .FirstOrDefaultAsync();
            return View(weightEntry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WeightID,Weight,Timestamp")] WeightEntry weightEntry)
        {
            if (ModelState.IsValid)
            { 
                var userId = _userManager.GetUserId(User);
                var existingWeightEntry = await _context.WeightEntries
                                                  .Where(f => f.WeightID == id && f.Id == userId)
                                                  .FirstOrDefaultAsync();

                existingWeightEntry.Weight = weightEntry.Weight;

                _context.Update(existingWeightEntry);
                await _context.SaveChangesAsync();

                // redirect to details page of item after editing item
                return RedirectToAction("Details", new { id = weightEntry.WeightID });
            }
            return View();
        }
    }
}

DigiGymWebApp_HDip/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@{
    string userRole = "Guest"; 

    if (User.IsInRole("Admin"))
    {
        userRole = "Admin";
    }
    else if (User.IsInRole("Trainer"))
    {
        userRole = "Trainer";
    }
    else if (User.IsInRole("Client"))
    {
        userRole = "Client";
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DigiGymWebApp_HDip</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap /dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DigiGymWebApp_HDip.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DigiGym</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between mx-4">
                    <ul class="navbar-nav flex-grow-1">

                        @if (userRole == "Trainer")
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Trainer Zone
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Trainer" asp-action="Requests">Message Requests</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Message" asp-action="Messages">My Replies</a>

                               
                            </div>
                        </li>
                        }
                        else if (userRole == "Client")
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Client Zone
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Client" asp-action="Profile">Profile</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Food" asp-action="FoodDiary">Food</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Workout" asp-action="Workouts">Workouts</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Weight" asp-action="WeightEntries">Weight</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Water" asp-action="WaterEntries">Water</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="" asp-controller="Message" asp-action="Messages">Messages</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Weight" asp-action="Chart">Weight Chart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Water" asp-action="Chart">Daily Water Chart</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Food" asp-action="FoodDiary">Daily Food Chart</a>
                        </li>
                        }
                        else if (userRole == "Admin")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin Center
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Admins">Admins List</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Trainers">Trainers List</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Clients">Clients List</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="Users">All Users List</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="PendingApproval">Pending Approval</a>
                                </div>
                            </li>
                        }
                        else
                        {

                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
        </nav>
    </header>
        <main role="main">
            @RenderBody()
        </main>
    <footer class="border-top footer">
        <div class="container text-light">
            &copy; 2024 - DigiGym
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* needed for mobile hamburger *@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-b9j6l/1G3Y6FLU4PZ6cZLRGnb8wO2Hl6HjzO2xj6w6W2nHbG1I6O4W3e1pH0WZtx" crossorigin="anonymous"></script>
    <script src="~/js/chart.js" asp-append-version="true"></script>
    <script src="~/js/pie.js" asp-append-version="true"></script>
    <script src="~/js/water.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>